basepath: '../data/sapien_data'
synthetic: True
extra_dims: 0
temporal: False
num_frames: 100
glasses:
    sym: False
    type: revolute
    num_parts: 3
    num_joints: 2
    tree: [2, 2, -1]  # the parent parts
    exemplar: '101300'
    parts_map: [[0], [1], [2]]
    test_list: ['101839', '101848', '101860', '101326', '101868', '102591', '102596', '103028']
    train_list: # Nothing for None
    augment_idx:
        x: [-1, -1, -1]
        y: [-1, 0, 0]
        z: [-1, 0, -1]   # legs should be of the same length (z)
    main_axis: [1, 1]

scissors:
    sym: False
    type: revolute
    num_parts: 2
    num_joints: 1
    tree: [-1, 0]
    parts_map: [[0], [1]]
    test_list: ['10559', '10564', '11029']
    train_list:
    augment_idx:  # global scale
        x: [-1, 0]
        y: [-1, 0]
        z: [-1, 0]
    main_axis: [1]

drawers:
    sym: False
    type: prismatic
    num_parts: 4
    num_joints: 3
    tree: [3, 3, 3, -1]
    parts_map: [[0], [1], [2], [3]]
    test_list: ['46440', '46123']
    train_list:
    augment_idx:  # global scale
        x: [-1, 0, 0, 0]
        y: [-1, 0, 0, 0]
        z: [-1, 0, 0, 0]
    main_axis: [2, 2, 2]

laptop:
    sym: False
    type: revolute
    num_parts: 2
    num_joints: 1
    tree: [-1, 0]
    parts_map: [[0], [1]]
    test_list: ['10101', '10270', '10356', '11156', '11405', '11581']
    train_list:
    augment_idx:
        x: [-1, 0]  # the axis
        y: [-1, -1]  # thickness
        z: [-1, 0]  # length
    main_axis: [0]





